GET http://localhost:3001/api/persons

###s

GET http://localhost:3001/api/persons/2

###
DELETE http://localhost:3001/api/persons/6233dd04c5187ceb6fe79406

### 
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arjun",
  "number": "2323123"
}